import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
      },
      spacing: {
        '0': '0',
        '1': '0.1rem',
        '2': '0.2rem',
        '3': '0.3rem',
        '4': '0.4rem',
        '5': '0.5rem',
        '6': '0.6rem',
        '7': '0.7rem',
        '8': '0.8rem',
        '9': '0.9rem',
        '10': '1rem',
        '11': '1.1rem',
        '12': '1.2rem',
        '13': '1.3rem',
        '14': '1.4rem',
        '15': '1.5rem',
        '16': '1.6rem',
        '17': '1.7rem',
        '18': '1.8rem',
        '19': '1.9rem',
        '20': '2rem',
        '21': '2.1rem',
        '22': '2.2rem',
        '23': '2.3rem',
        '24': '2.4rem',
        '25': '2.5rem',
        '26': '2.6rem',
        '27': '2.7rem',
        '28': '2.8rem',
        '29': '2.9rem',
        '30': '3rem',
        '31': '3.1rem',
        '32': '3.2rem',
        '33': '3.3rem',
        '34': '3.4rem',
        '35': '3.5rem',
        '36': '3.6rem',
        '37': '3.7rem',
        '38': '3.8rem',
        '39': '3.9rem',
        '40': '4rem',
        '41': '4.1rem',
        '42': '4.2rem',
        '43': '4.3rem',
        '44': '4.4rem',
        '45': '4.5rem',
        '46': '4.6rem',
        '47': '4.7rem',
        '48': '4.8rem',
        '49': '4.9rem',
        '50': '5rem',
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;

export default config;
